-- =============================================================================
-- Migration 004: Player Rating History Table
-- Date: 2026-03-01
-- Description: Adds table to track player rating changes per tournament
--              Enables single-pass chronological rating calculation and
--              rating graphs/history views for players
--
-- Changes:
--   1. Create player_rating_history table
--   2. Add indexes for efficient lookups
-- =============================================================================

-- 1. Create player_rating_history table
-- Stores rating before/after each tournament for each player
CREATE TABLE IF NOT EXISTS player_rating_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(player_id) ON DELETE CASCADE,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(tournament_id) ON DELETE CASCADE,
    rating_before INTEGER NOT NULL,
    rating_after INTEGER NOT NULL,
    rating_change INTEGER NOT NULL,
    events_played INTEGER NOT NULL,  -- Number of events played up to and including this one
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(player_id, tournament_id)
);

-- 2. Create indexes for efficient lookups
CREATE INDEX IF NOT EXISTS idx_rating_history_player ON player_rating_history(player_id);
CREATE INDEX IF NOT EXISTS idx_rating_history_tournament ON player_rating_history(tournament_id);

-- 3. Create index for chronological queries (player history over time)
CREATE INDEX IF NOT EXISTS idx_rating_history_player_event ON player_rating_history(player_id, tournament_id);
