"""
Migrate data from local DuckDB to Neon PostgreSQL.

Reads all tables from data/local.duckdb and inserts them into a Neon
Postgres database, respecting foreign key order (parents before children).

Usage:
    python scripts/migrate_to_neon.py                    # migrate data
    python scripts/migrate_to_neon.py --dry-run           # preview only
    python scripts/migrate_to_neon.py --schema-only       # create tables first
    python scripts/migrate_to_neon.py --schema-only --dry-run  # show schema SQL

Prerequisites:
    pip install duckdb psycopg2-binary python-dotenv

Environment variables (.env):
    NEON_HOST          - Neon Postgres hostname (required)
    NEON_DATABASE      - Database name (default: "neondb")
    NEON_USER          - Postgres user (required)
    NEON_PASSWORD      - Postgres password (required)
"""

import os
import sys
import argparse
import duckdb
import psycopg2
from psycopg2.extras import execute_values
from pathlib import Path
from dotenv import load_dotenv
from datetime import date, datetime
from decimal import Decimal

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

LOCAL_DB = "data/local.duckdb"
SCHEMA_FILE = "db/schema.sql"

# Tables in FK-safe order (parents before children)
TABLES = [
    "scenes",
    "stores",
    "store_schedules",
    "formats",
    "cards",
    "players",
    "deck_archetypes",
    "archetype_cards",
    "deck_requests",
    "tournaments",
    "results",
    "matches",
    "ingestion_log",
    "player_ratings_cache",
    "store_ratings_cache",
    "rating_snapshots",
    "limitless_deck_map",
    "limitless_sync_state",
    "admin_users",
]

# Tables that have auto-increment (GENERATED BY DEFAULT AS IDENTITY) columns
# Format: (table_name, id_column_name)
IDENTITY_TABLES = [
    ("scenes", "scene_id"),
    ("stores", "store_id"),
    ("store_schedules", "schedule_id"),
    ("players", "player_id"),
    ("deck_archetypes", "archetype_id"),
    ("deck_requests", "request_id"),
    ("tournaments", "tournament_id"),
    ("results", "result_id"),
    ("matches", "match_id"),
    ("ingestion_log", "log_id"),
    ("admin_users", "user_id"),
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def connect_duckdb():
    """Connect to local DuckDB in read-only mode."""
    db_path = Path(LOCAL_DB)
    if not db_path.exists():
        print(f"Error: Local database not found at {db_path.absolute()}")
        sys.exit(1)
    return duckdb.connect(str(db_path), read_only=True)


def connect_neon():
    """Connect to Neon Postgres using env vars."""
    host = os.getenv("NEON_HOST")
    database = os.getenv("NEON_DATABASE", "neondb")
    user = os.getenv("NEON_USER")
    password = os.getenv("NEON_PASSWORD")

    missing = []
    if not host:
        missing.append("NEON_HOST")
    if not user:
        missing.append("NEON_USER")
    if not password:
        missing.append("NEON_PASSWORD")
    if missing:
        print(f"Error: Missing required env vars: {', '.join(missing)}")
        print("Set them in your .env file.")
        sys.exit(1)

    return psycopg2.connect(
        host=host,
        port=5432,
        dbname=database,
        user=user,
        password=password,
        sslmode="require",
    )


def convert_row(row):
    """Convert a single row's values for Postgres compatibility.

    DuckDB may return types that psycopg2 doesn't handle automatically:
    - Decimal -> float (for cleaner insert; Postgres casts back)
    - Other types (bool, date, datetime, str, int, None) pass through fine.
    """
    converted = []
    for val in row:
        if isinstance(val, Decimal):
            converted.append(float(val))
        else:
            converted.append(val)
    return tuple(converted)


# ---------------------------------------------------------------------------
# Schema operations
# ---------------------------------------------------------------------------


def run_schema(pg_conn, dry_run=False):
    """Execute the Postgres schema SQL file on Neon."""
    schema_path = Path(SCHEMA_FILE)
    if not schema_path.exists():
        print(f"Error: Schema file not found at {schema_path.absolute()}")
        sys.exit(1)

    with open(schema_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Split on semicolons, filter out empty/comment-only statements
    statements = content.split(";")
    valid_stmts = []
    for stmt in statements:
        cleaned = stmt.strip()
        # Remove pure comment lines to check if anything real remains
        lines = [
            line
            for line in cleaned.split("\n")
            if line.strip() and not line.strip().startswith("--")
        ]
        if lines:
            valid_stmts.append(cleaned)

    print(f"\nSchema file: {SCHEMA_FILE}")
    print(f"Statements to execute: {len(valid_stmts)}")

    if dry_run:
        print("\n[DRY RUN] Schema statements that would be executed:\n")
        for i, stmt in enumerate(valid_stmts, 1):
            # Show first line of each statement for readability
            first_line = stmt.split("\n")[0].strip()
            # Remove leading comment lines to find the actual SQL
            for line in stmt.split("\n"):
                stripped = line.strip()
                if stripped and not stripped.startswith("--"):
                    first_line = stripped
                    break
            print(f"  {i:3d}. {first_line[:100]}")
        print(f"\n[DRY RUN] Would execute {len(valid_stmts)} statements. No changes made.")
        return

    cur = pg_conn.cursor()
    success = 0
    errors = 0

    for i, stmt in enumerate(valid_stmts, 1):
        try:
            cur.execute(stmt)
            pg_conn.commit()
            success += 1
        except Exception as e:
            pg_conn.rollback()
            err_msg = str(e).strip().split("\n")[0]
            # Suppress "already exists" noise
            if "already exists" in err_msg.lower():
                success += 1
            else:
                errors += 1
                print(f"  Warning (stmt {i}): {err_msg[:120]}")

    cur.close()
    print(f"Schema applied: {success} succeeded, {errors} errors")


# ---------------------------------------------------------------------------
# Data migration
# ---------------------------------------------------------------------------


def migrate_table(duck_conn, pg_conn, table, dry_run=False):
    """Migrate a single table from DuckDB to Postgres.

    Returns the number of rows migrated (or that would be migrated in dry-run).
    Raises on error so the caller can handle it.
    """
    # Read all rows from DuckDB
    result = duck_conn.execute(f"SELECT * FROM {table}")
    columns = [desc[0] for desc in result.description]
    rows = result.fetchall()

    if not rows:
        print(f"  {table}: skipped (0 rows)")
        return 0

    row_count = len(rows)

    if dry_run:
        print(f"  {table}: {row_count} rows (would migrate)")
        return row_count

    cur = pg_conn.cursor()

    try:
        # Truncate existing data (CASCADE to handle FK references)
        cur.execute(f"TRUNCATE TABLE {table} CASCADE")

        # Build INSERT template
        cols_str = ", ".join(columns)
        template = f"({', '.join(['%s'] * len(columns))})"

        # Convert rows for Postgres compatibility
        converted_rows = [convert_row(row) for row in rows]

        # Bulk insert using execute_values for speed
        insert_sql = f"INSERT INTO {table} ({cols_str}) VALUES %s"
        execute_values(cur, insert_sql, converted_rows, template=template, page_size=1000)

        pg_conn.commit()
        print(f"  {table}: {row_count} rows migrated")
        return row_count

    except Exception:
        pg_conn.rollback()
        raise
    finally:
        cur.close()


def reset_sequences(pg_conn, dry_run=False):
    """Reset identity sequences for auto-increment tables to MAX(id) + 1."""
    print("\nResetting identity sequences...")
    cur = pg_conn.cursor()

    for table, id_col in IDENTITY_TABLES:
        sql = (
            f"SELECT setval("
            f"pg_get_serial_sequence('{table}', '{id_col}'), "
            f"COALESCE((SELECT MAX({id_col}) FROM {table}), 0) + 1, "
            f"false)"
        )

        if dry_run:
            print(f"  {table}.{id_col}: would reset sequence")
            continue

        try:
            cur.execute(sql)
            # Fetch the new sequence value for reporting
            new_val = cur.fetchone()[0]
            pg_conn.commit()
            print(f"  {table}.{id_col}: sequence set to {new_val}")
        except Exception as e:
            pg_conn.rollback()
            err_msg = str(e).strip().split("\n")[0]
            print(f"  {table}.{id_col}: ERROR - {err_msg[:100]}")

    cur.close()


def print_summary(duck_conn, pg_conn, dry_run=False):
    """Print row counts from both databases and flag mismatches."""
    print("\n" + "=" * 65)
    print("MIGRATION SUMMARY")
    print("=" * 65)
    print(f"{'Table':<30} {'DuckDB':>8} {'Postgres':>8} {'Status':>10}")
    print("-" * 65)

    all_match = True

    for table in TABLES:
        # DuckDB count
        try:
            duck_count = duck_conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        except Exception:
            duck_count = "ERR"

        # Postgres count
        if dry_run:
            pg_count = "N/A"
            status = "dry-run"
        else:
            try:
                cur = pg_conn.cursor()
                cur.execute(f"SELECT COUNT(*) FROM {table}")
                pg_count = cur.fetchone()[0]
                cur.close()
            except Exception:
                pg_count = "ERR"

            if isinstance(duck_count, int) and isinstance(pg_count, int):
                if duck_count == pg_count:
                    status = "OK"
                else:
                    status = "MISMATCH"
                    all_match = False
            else:
                status = "ERROR"
                all_match = False

        print(f"  {table:<28} {str(duck_count):>8} {str(pg_count):>8} {status:>10}")

    print("-" * 65)

    if dry_run:
        print("Mode: DRY RUN (no data was written)")
    elif all_match:
        print("All tables match. Migration successful!")
    else:
        print("WARNING: Some tables have mismatches. Check errors above.")

    print("=" * 65)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Migrate data from local DuckDB to Neon PostgreSQL."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be migrated without writing any data.",
    )
    parser.add_argument(
        "--schema-only",
        action="store_true",
        help="Run the Postgres schema SQL file on Neon before migrating data.",
    )
    args = parser.parse_args()

    # Load .env
    load_dotenv()

    print("=" * 65)
    print("DigiLab - DuckDB to Neon PostgreSQL Migration")
    print("=" * 65)

    if args.dry_run:
        print("MODE: DRY RUN (no changes will be made)")

    # -----------------------------------------------------------------------
    # Schema-only mode
    # -----------------------------------------------------------------------
    if args.schema_only:
        if args.dry_run:
            # Just show schema statements, no Postgres connection needed
            run_schema(None, dry_run=True)
            return

        print("\nConnecting to Neon Postgres...")
        pg_conn = connect_neon()
        print("  Connected.")

        run_schema(pg_conn, dry_run=False)
        pg_conn.close()
        print("\nDone. Schema applied to Neon.")
        return

    # -----------------------------------------------------------------------
    # Data migration mode
    # -----------------------------------------------------------------------
    print("\n[1/5] Connecting to local DuckDB...")
    duck_conn = connect_duckdb()
    print(f"  Connected: {Path(LOCAL_DB).absolute()}")

    pg_conn = None
    if not args.dry_run:
        print("\n[2/5] Connecting to Neon Postgres...")
        pg_conn = connect_neon()
        print("  Connected.")
    else:
        print("\n[2/5] Skipping Neon connection (dry run)")

    # Migrate each table
    print(f"\n[3/5] Migrating {len(TABLES)} tables...")
    total_rows = 0
    errors = []

    for table in TABLES:
        try:
            count = migrate_table(duck_conn, pg_conn, table, dry_run=args.dry_run)
            total_rows += count
        except Exception as e:
            err_msg = str(e).strip().split("\n")[0]
            print(f"  {table}: ERROR - {err_msg[:120]}")
            errors.append((table, err_msg))

    print(f"\n  Total: {total_rows} rows {'would be ' if args.dry_run else ''}migrated")
    if errors:
        print(f"  Errors: {len(errors)} table(s) failed")

    # Reset identity sequences
    if not args.dry_run:
        print("\n[4/5] Resetting identity sequences...")
        reset_sequences(pg_conn, dry_run=args.dry_run)
    else:
        print("\n[4/5] Resetting identity sequences...")
        reset_sequences(None, dry_run=True)

    # Summary
    print("\n[5/5] Verifying migration...")
    print_summary(duck_conn, pg_conn, dry_run=args.dry_run)

    # Cleanup
    duck_conn.close()
    if pg_conn:
        pg_conn.close()


if __name__ == "__main__":
    main()
