# Run migration 004 - Player Rating History table
# Usage: source("scripts/run_migration_004.R")

library(DBI)
library(RPostgres)
library(dotenv)

load_dot_env()

message("Connecting to database...")

con <- dbConnect(
  Postgres(),
  host = Sys.getenv("NEON_HOST"),
  dbname = Sys.getenv("NEON_DATABASE"),
  user = Sys.getenv("NEON_USER"),
  password = Sys.getenv("NEON_PASSWORD"),
  sslmode = "require"
)

message("Running migration 004: player_rating_history table...")

# Create the table
dbExecute(con, "
CREATE TABLE IF NOT EXISTS player_rating_history (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(player_id) ON DELETE CASCADE,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(tournament_id) ON DELETE CASCADE,
    rating_before INTEGER NOT NULL,
    rating_after INTEGER NOT NULL,
    rating_change INTEGER NOT NULL,
    events_played INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(player_id, tournament_id)
)
")
message("  Created player_rating_history table")

# Create indexes
dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_rating_history_player ON player_rating_history(player_id)")
message("  Created idx_rating_history_player index")

dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_rating_history_tournament ON player_rating_history(tournament_id)")
message("  Created idx_rating_history_tournament index")

dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_rating_history_player_event ON player_rating_history(player_id, tournament_id)")
message("  Created idx_rating_history_player_event index")

# Verify
result <- dbGetQuery(con, "SELECT COUNT(*) as count FROM information_schema.tables WHERE table_name = 'player_rating_history'")
if (result$count[1] > 0) {
  message("\nMigration 004 complete! Table player_rating_history created.")
} else {
  message("\nERROR: Migration failed - table not found!")
}

dbDisconnect(con)
message("Database connection closed.")
